version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
