window.importantItems = [
    "Abyss_Shriek",
    "Awoken_Dream_Nail",
    "Crystal_Heart",
    "Cyclone_Slash",
    "Dash_Slash",
    "Descending_Dark",
    "Desolate_Dive",
    "Dream_Gate",
    "Dream_Nail",
    "Dreamer",
    "Elegant_Key",
    "Great_Slash",
    "Herrah",
    "Howling_Wraiths",
    "Isma's_Tear",
    "King_Fragment",
    "King's_Brand",
    "Love_Key",
    "Lumafly_Lantern",
    "Lurien",
    "Mantis_Claw",
    "Monarch_Wings",
    "Monomon",
    "Mothwing_Cloak",
    "Queen_Fragment",
    "Shade_Cloak",
    "Shade_Soul",
    "Shaman_Stone",
    "Shopkeeper's_Key",
    "Tram_Pass",
    "Vengeful_Spirit",
    "Void_Heart"
]

window.progressiveItemBase = {
    "Abyss_Shriek": "Howling_Wraiths",
    "Awoken_Dream_Nail": "Dream_Nail",
    "Descending_Dark": "Desolate_Dive",
    "Dream_Gate": "Dream_Nail",
    "Queen_Fragment": "White_Fragment",
    "King_Fragment": "White_Fragment",
    "Shade_Cloak": "Mothwing_Cloak",
    "Shade_Soul": "Vengeful_Spirit",
    "Void_Heart": "White_Fragment"
}